/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AwButtonMode, AwButtonStatus } from "./components/aw-button/aw-button.model";
export namespace Components {
    interface AwButton {
        /**
          * Boolean to indicate if button is disabled
         */
        "disabled": boolean;
        /**
          * Optional ID to be attached on button
         */
        "identifier": string;
        /**
          * Text to show inside button
         */
        "label": string;
        /**
          * Mode of button (style)
         */
        "mode": AwButtonMode;
        /**
          * The status of button (color)
         */
        "status": AwButtonStatus;
    }
}
declare global {
    interface HTMLAwButtonElement extends Components.AwButton, HTMLStencilElement {
    }
    var HTMLAwButtonElement: {
        prototype: HTMLAwButtonElement;
        new (): HTMLAwButtonElement;
    };
    interface HTMLElementTagNameMap {
        "aw-button": HTMLAwButtonElement;
    }
}
declare namespace LocalJSX {
    interface AwButton {
        /**
          * Boolean to indicate if button is disabled
         */
        "disabled"?: boolean;
        /**
          * Optional ID to be attached on button
         */
        "identifier"?: string;
        /**
          * Text to show inside button
         */
        "label"?: string;
        /**
          * Mode of button (style)
         */
        "mode"?: AwButtonMode;
        /**
          * The status of button (color)
         */
        "status"?: AwButtonStatus;
    }
    interface IntrinsicElements {
        "aw-button": AwButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aw-button": LocalJSX.AwButton & JSXBase.HTMLAttributes<HTMLAwButtonElement>;
        }
    }
}
